spring:
   datasource:
     username: api
     password: 1234
     url: jdbc:oracle:thin:@//localhost:1521/xe
     driver-class-name: oracle.jdbc.driver.OracleDriver
     
   jpa:    show-sql: true    hibernate:      ddl-auto: update